server:
  port: 8080

spring:
  application:
    name: auth
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql=true:
    hibernate:
      ddl-auto: none

  datasource:
    username: user-db
    password: kt^#54hfff@%*t53gfhj
    url: jdbc:postgresql://localhost:5432/itmusik
    driver-class-name: org.postgresql.Driver

  main:
    allow-circular-references: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  config:
    import:
      optional:configserver:http://config-server:8888

springdoc:
  api-docs:
    path: /auth/v3/api-docs

  swagger-ui:
    path: /auth/swagger-ui.html

  endpoints:
    web:
      exposure:
        include: /*

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}

logging:
  level:
    web: trace

management:
  endpoints:
    web:
      exposure:
        include: refresh