server:
  port: 8084

spring:
  application:
    name: scrobble

  r2dbc:
    password: kt^#54hfff@%*t53gfhj
    username: user-db
    url: r2dbc:postgresql://localhost:5432/itmusik

#  datasource:
#    username: user-db
#    password: kt^#54hfff@%*t53gfhj
#    url: jdbc:postgresql://localhost:5432/itmusik
#    driver-class-name: org.postgresql.Driver

  main:
    allow-circular-references: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  config:
    import:
      optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka}