#!/bin/bash
cd ..
CL='\033[0;33m'
NC='\033[0m'
echo -e "${CL}gradle clean:${NC}"
./gradlew clean
echo
echo -e "${CL}stop docker containers:${NC}"
docker container stop auth music user postgres eureka-server config-server gateway scrobble song zookeeper broker notification
echo
echo -e "${CL}remove docker containers:${NC}"
docker container rm auth music user postgres eureka-server config-server gateway scrobble song zookeeper broker notification
echo
echo -e "${CL}remove docker images:${NC}"
docker image rm auth music user eureka-server config-server gateway scrobble song notification