#!/bin/bash
cd ..
CL='\033[0;33m'
NC='\033[0m'
echo -e "${CL}gradle clean:${NC}"
./gradlew clean
echo
echo -e "${CL}stop docker containers:${NC}"
docker container stop app postgres eureka-server gateway
echo
echo -e "${CL}remove docker containers:${NC}"
docker container rm app postgres eureka-server gateway
echo
echo -e "${CL}remove docker images:${NC}"
docker image rm app postgres eureka-server gateway