name: run tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Test
        run: |
          docker-compose up -d postgres
          cat ./scrobble/src/main/resources/application-test.yaml > ./scrobble/src/main/resources/application.yaml
          cat ./song/src/main/resources/application-test.yaml > ./song/src/main/resources/application.yaml
          ./gradlew test